### ISSUE TITLE
使わないコードは書かないようにしよう

### ISSUE THREAD

**Issue by norotime** [emi-sammy/voice_logs#5]
https://github.com/emi-sammy/voice_logs/blob/77706190900720ebfc5c6438734ac64ccb68bb38/app/controllers/staffs_controller.rb#L36

@emi-sammy scaffoldでjsonそのまま、は思考停止しているように感じられます。
よくないですよ〜

**Comment by emi-sammy** [comment]
不要なコードを削除しました
