### ISSUE TITLE
意味のないコミットメッセージは絶対にやめよう

### ISSUE THREAD

**Issue by norotime** [emi-sammy/voice_logs#9]
![2018-09-16 17 57 41](https://user-images.githubusercontent.com/7435505/45594703-0a342a00-b9da-11e8-859e-374111106510.png)

@emi-sammy また、内容と整合していないです。チーム開発の鉄則はコミュニケーションです。コミュニケーションの一つであるホウレンソウ。それがこのコミットメッセージです。
（新人君が、いつも同じ日報を書いてきたら、怒りますよね？）というイメージです。笑

**Comment by emi-sammy** [comment]
今後は、安易なエッセージにならないよう留意いたします。
